[package]
name = "rust-axum-mongo-example-adapter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-axum-mongo-example-kernel = { path = "../rust-axum-mongo-example-kernel" }