version: "3"

services:
  mongo:
    container_name: rust-axum-mongo
    image: mongo:7.0.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: example
    ports:
      - '27017:27017'
    volumes:
      - ./mock/mongo/initdb.d:/docker-entrypoint-initdb.d
      - ./mongo:/data/db
      - ./mongo:/data/configdb

  mongo-express:
    container_name: mongo_express
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      - mongo