on: [push]

name: CI

env:
  PORT: 8080

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
          # args: -p rust-axum-driver --lib
        env:
          PORT: ${{ env.PORT }}