on: [push]

name: CI

env:
  PORT: 8080
  HOST: 127.0.0.1
  DATABASE_URL: mongodb://root:password@localhost:27017

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          PORT: ${{ env.PORT }}
          HOST: ${{ env.HOST }}
          DATABASE_URL: ${{ env.DATABASE_URL }}